# Hyperparamter Optimization

## Importing the libraries

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [6]:
data = pd.read_csv("C:/Users/user 1/Documents/Fall _ Spring 2022-2023/Course_Work/Fall 2023/Practical ML/Homeworks or Reflections/Reflection_1/Classification/Data.csv")

data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [7]:
X = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [12]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

### ML Classifiers

### Randomized SearchCV

#### Logistic Regression model 

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import RandomizedSearchCV

from sklearn.linear_model import LogisticRegression
mod_Lr = LogisticRegression()
mod_Lr.fit(X_train, y_train)
y_pred = mod_Lr.predict(X_test)
y_train_pred = mod_Lr.predict(X_train)

print("Accuracy of Train Data: ", accuracy_score(y_train, y_train_pred)*100) 
print("Accuracy of Test Data: ", accuracy_score(y_test, y_pred)*100)

# Note that hyperparamter did not improve the model, hence I used the default hyperparameters.

Accuracy of Train Data:  98.046875
Accuracy of Test Data:  94.73684210526315


##### Hyperparameter Tuning of LR

In [19]:
parameters = [{
                "C" : [0.1, 0.2,0.3,0.4, 0.5,0.6,0.7,0.8,0.9,1],
               "solver": ["lbfgs", "newton-cg", "liblinear", "sag", "saga"],
               "max_iter" : [50, 100, 200, 1000, 2500, 5000]
       }]

random_search= RandomizedSearchCV(mod_Lr, param_distributions = parameters, scoring = "accuracy", cv = 10, n_jobs = -1)

random_search.fit(X_train,y_train)
best_accuracy = random_search.best_score_
best_paramters = random_search.best_params_

print("Best Accuracy: {:.2f} %".format((best_accuracy)*100))
print("Best Paramters:",best_paramters)

Best Accuracy: 97.27 %
Best Paramters: {'solver': 'sag', 'max_iter': 50, 'C': 0.9}


C:\Users\user 1\anaconda3\New_Anaconda\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [20]:
cm = confusion_matrix(y_test, y_pred)
cm1 = confusion_matrix(y_train, y_train_pred)
print(cm)
print(cm1)

[[103   4]
 [  5  59]]
[[332   5]
 [  5 170]]


##### Support Vector Machines

In [30]:
from sklearn import svm
mod_SVC = svm.SVC()
mod_SVC = mod_SVC.fit(X_train, y_train)
y_pred = mod_SVC.predict(X_test)
y_train_pred = mod_SVC.predict(X_train)
print("Accuracy of Train Data: ", accuracy_score(y_train, y_train_pred)*100) 
print("Accuracy of Test Data: ", accuracy_score(y_test, y_pred)*100) 

# Based on the outcome of the model, the default hyperparameters will be used.

Accuracy of Train Data:  97.8515625
Accuracy of Test Data:  95.32163742690058


In [28]:
parameters = [{"C" : [0.1, 0.2,0.3,0.4, 0.5,0.6,0.7,0.8,0.9,1],
               "kernel": ["linear", "rbf", "sigmoid"],
               "gamma": [(0.01 + x / 100) for x in range(10, 90)]
       }]

random_search9 = RandomizedSearchCV(mod_SVC, param_distributions = parameters, n_iter = 5, scoring = "accuracy", cv = 10, n_jobs = -1)

random_search9.fit(X_train,y_train)
best_accuracy = random_search9.best_score_
best_paramters = random_search9.best_params_

print("Best Accuracy: {:.2f} %".format((best_accuracy)*100))
print("Best Paramters:",best_paramters)

Best Accuracy: 97.27 %
Best Paramters: {'kernel': 'linear', 'gamma': 0.65, 'C': 0.2}


In [31]:
cm = confusion_matrix(y_test, y_pred)
cm2 = confusion_matrix(y_train, y_train_pred)
print(cm)
print(cm2)

[[102   5]
 [  3  61]]
[[329   8]
 [  3 172]]


#### Decision Tree

In [34]:
from sklearn.tree import DecisionTreeClassifier
mod_DT = DecisionTreeClassifier(min_samples_split = 10, min_samples_leaf = 4, criterion = "gini",
                                 random_state = 0)
mod_DT.fit(X_train, y_train)
y_pred1 = mod_DT.predict(X_test)
y_train_pred1 = mod_DT.predict(X_train)

print("Accuracy of Train Data: ", accuracy_score(y_train, y_train_pred1)*100) 
print("Accuracy of Test Data: ", accuracy_score(y_test, y_pred1)*100)

Accuracy of Train Data:  97.8515625
Accuracy of Test Data:  95.32163742690058


##### Hyperparamter Tuning of Decision Tree

In [25]:
parameters = [{"min_samples_leaf": [1,2,3,4,5,6,7,8,9],
              "min_samples_split": [int(x) for x in np.linspace(10, 200, 5)],
              "criterion": ["gini", "entropy"]}]
random_search1 = RandomizedSearchCV(mod_DT, param_distributions = parameters, scoring = "accuracy", 
                                   cv = 10, n_jobs = -1)

random_search1.fit(X_train,y_train)
best_accuracy = random_search1.best_score_
best_paramters = random_search1.best_params_

print("Best Accuracy: {:.2f} %".format((best_accuracy)*100))
print("Best Paramters:",best_paramters)

Best Accuracy: 95.90 %
Best Paramters: {'min_samples_split': 10, 'min_samples_leaf': 4, 'criterion': 'gini'}


In [39]:
cm3 = confusion_matrix(y_test, y_pred1)
cm4 = confusion_matrix(y_train, y_train_pred1)
print(cm3)
print(cm4)

[[105   2]
 [  6  58]]
[[332   5]
 [  6 169]]


#### Random Forest

In [38]:
from sklearn.ensemble import RandomForestClassifier
mod_RF = RandomForestClassifier(n_estimators = 3000, criterion = "entropy", 
                                min_samples_split = 200, min_samples_leaf = 2, random_state = 0)
mod_RF.fit(X_train, y_train)
y_pred2 = mod_RF.predict(X_test)
y_train_pred2 = mod_RF.predict(X_train)

print("Accuracy of Train Data: ", accuracy_score(y_train, y_train_pred2)*100) 
print("Accuracy of Test Data: ", accuracy_score(y_test, y_pred2)*100)

Accuracy of Train Data:  97.65625
Accuracy of Test Data:  95.90643274853801


In [89]:
from sklearn.model_selection import RandomizedSearchCV

parameters = [{"min_samples_leaf": [1,2,3,4,5,6,7,8,9],
              "min_samples_split": [int(x) for x in np.linspace(10, 200, 5)],
              "n_estimators": [100,150,200,300,400,500,600,700,800,900, 1000, 2000, 3000, 3300],
              "criterion": ["gini", "entropy"]}]
random_search = RandomizedSearchCV(mod_RF, param_distributions = parameters, scoring = "accuracy", 
                                   cv = 10, n_jobs = -1)

random_search.fit(X_train,y_train)
best_accuracy = random_search.best_score_
best_paramters = random_search.best_params_

print("Best Accuracy: {:.2f} %".format((best_accuracy)*100))
print("Best Paramters:",best_paramters)

Best Accuracy: 97.46 %
Best Paramters: {'n_estimators': 3000, 'min_samples_split': 200, 'min_samples_leaf': 2, 'criterion': 'entropy'}


In [40]:
cm5 = confusion_matrix(y_test, y_pred2)
cm6 = confusion_matrix(y_train, y_train_pred2)
print(cm5)
print(cm6)

[[102   5]
 [  2  62]]
[[327  10]
 [  2 173]]


### Bayesian Optimization

In [2]:
pip install scikit-optimize

     -------------------------------------- 100.3/100.3 kB 5.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
from skopt import BayesSearchCV
from skopt.space import Integer, Categorical

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score

from sklearn.linear_model import LogisticRegression
mod_Lr_BO = LogisticRegression(C = 0.4, max_iter = 9000, solver = "liblinear")
mod_Lr_BO.fit(X_train, y_train)
y_pred = mod_Lr_BO.predict(X_test)
y_train_pred = mod_Lr_BO.predict(X_train)

print("Accuracy of Train Data: ", accuracy_score(y_train, y_train_pred)*100) 
print("Accuracy of Test Data: ", accuracy_score(y_test, y_pred)*100)

Accuracy of Train Data:  97.4609375
Accuracy of Test Data:  93.56725146198829


In [15]:
search_space = [{
                "C" : [0.1, 0.2,0.3,0.4, 0.5,0.6,0.7,0.8,0.9,1],
               "solver": ["lbfgs", "newton-cg", "liblinear", "sag", "saga"],
               "max_iter" : [50, 100, 200, 1000, 2500, 5000, 5500, 6000, 6500, 7000, 8000, 9000]
       }]

Bayes_search = BayesSearchCV(mod_Lr_BO, search_space, scoring = "accuracy", cv = 10, n_jobs = -1)

Bayes_search.fit(X_train,y_train)
best_accuracy = Bayes_search.best_score_
best_paramters = Bayes_search.best_params_

print("Best Accuracy: {:.2f} %".format((best_accuracy)*100))
print("Best Paramters:",best_paramters)

Best Accuracy: 97.27 %
Best Paramters: OrderedDict([('C', 0.4), ('max_iter', 9000), ('solver', 'liblinear')])


In [19]:
from sklearn import svm
mod_SVC = svm.SVC(C = 0.8, gamma = 0.18, kernel = "rbf")
mod_SVC = mod_SVC.fit(X_train, y_train)
y_pred3 = mod_SVC.predict(X_test)
y_train_pred3 = mod_SVC.predict(X_train)
print("Accuracy of Train Data: ", accuracy_score(y_train, y_train_pred3)*100) 
print("Accuracy of Test Data: ", accuracy_score(y_test, y_pred3)*100) 

Accuracy of Train Data:  99.609375
Accuracy of Test Data:  94.73684210526315


In [18]:
search_space = [{"C" : [0.1, 0.2,0.3,0.4, 0.5,0.6,0.7,0.8,0.9,1],
               "kernel": ["linear", "rbf", "sigmoid"],
               "gamma": [(0.01 + x / 100) for x in range(10, 90)]
       }]

Bayes_search1 = BayesSearchCV(mod_SVC, search_space, n_iter = 5, scoring = "accuracy", cv = 10, n_jobs = -1)

Bayes_search1.fit(X_train,y_train)
best_accuracy = Bayes_search1.best_score_
best_paramters = Bayes_search1.best_params_

print("Best Accuracy: {:.2f} %".format((best_accuracy)*100))
print("Best Paramters:",best_paramters)

Best Accuracy: 94.73 %
Best Paramters: OrderedDict([('C', 0.8), ('gamma', 0.18000000000000002), ('kernel', 'rbf')])


In [23]:
from sklearn.tree import DecisionTreeClassifier
mod_DT = DecisionTreeClassifier(min_samples_split = 10, min_samples_leaf = 4, criterion = "gini",
                                 random_state = 0)
mod_DT.fit(X_train, y_train)
y_pred3 = mod_DT.predict(X_test)
y_train_pred3 = mod_DT.predict(X_train)

print("Accuracy of Train Data: ", accuracy_score(y_train, y_train_pred3)*100) 
print("Accuracy of Test Data: ", accuracy_score(y_test, y_pred3)*100)

Accuracy of Train Data:  97.8515625
Accuracy of Test Data:  95.32163742690058


In [21]:
search_space = [{"min_samples_leaf": [1,2,3,4,5,6,7,8,9],
              "min_samples_split": [int(x) for x in np.linspace(10, 200, 5)],
              "criterion": ["gini", "entropy"]}]
Bayes_search2 = BayesSearchCV(mod_DT, search_space, scoring = "accuracy", cv = 10, n_jobs = -1)

Bayes_search2.fit(X_train,y_train)
best_accuracy = Bayes_search2.best_score_
best_paramters = Bayes_search2.best_params_

print("Best Accuracy: {:.2f} %".format((best_accuracy)*100))
print("Best Paramters:",best_paramters)

C:\Users\user 1\anaconda3\New_Anaconda\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
C:\Users\user 1\anaconda3\New_Anaconda\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
C:\Users\user 1\anaconda3\New_Anaconda\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
C:\Users\user 1\anaconda3\New_Anaconda\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
C:\Users\user 1\anaconda3\New_Anaconda\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point befor

Best Accuracy: 96.10 %
Best Paramters: OrderedDict([('criterion', 'gini'), ('min_samples_leaf', 4), ('min_samples_split', 10)])


In [26]:
from sklearn.ensemble import RandomForestClassifier
mod_RF = RandomForestClassifier(n_estimators = 600, criterion = "gini", 
                                min_samples_split = 200, min_samples_leaf = 6, random_state = 0)
mod_RF.fit(X_train, y_train)
y_pred4 = mod_RF.predict(X_test)
y_train_pred4 = mod_RF.predict(X_train)

print("Accuracy of Train Data: ", accuracy_score(y_train, y_train_pred4)*100) 
print("Accuracy of Test Data: ", accuracy_score(y_test, y_pred4)*100)

Accuracy of Train Data:  97.4609375
Accuracy of Test Data:  93.56725146198829


In [25]:
search_space = [{"min_samples_leaf": [1,2,3,4,5,6,7,8,9],
              "min_samples_split": [int(x) for x in np.linspace(10, 200, 5)],
              "n_estimators": [100,150,200,300,400,500,600,700,800,900, 1000, 2000, 3000, 3300],
              "criterion": ["gini", "entropy"]}]
Bayes_search3 = BayesSearchCV(mod_RF, search_space, scoring = "accuracy", cv = 10, n_jobs = -1)

Bayes_search3.fit(X_train,y_train)
best_accuracy = Bayes_search3.best_score_
best_paramters = Bayes_search3.best_params_

print("Best Accuracy: {:.2f} %".format((best_accuracy)*100))
print("Best Paramters:",best_paramters)

C:\Users\user 1\anaconda3\New_Anaconda\lib\site-packages\joblib\externals\loky\process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best Accuracy: 97.65 %
Best Paramters: OrderedDict([('criterion', 'gini'), ('min_samples_leaf', 6), ('min_samples_split', 200), ('n_estimators', 600)])


##### Discussions

In [ ]:
# Results

# Randomized SearchCV results

#   ML Algorithms                      Performance Comparison
                                   #Train            # Test

# Logistic Regression               98.05            94.74    
# Support Vector Machines           97.85            95.32
# Decision Tree                     97.85            95.32
# Random Forest                     97.66            95.91


# Bayesian SearchCV results

#   ML Algorithms                      Performance Comparison
                                   #Train            # Test

# Logistic Regression               97.46            93.57    
# Support Vector Machines           99.61            94.74
# Decision Tree                     97.85            95.85
# Random Forest                     97.46            93.57

In [ ]:
# The dataset used in this classification problem is also from one of the machine learning tutorial I did on Udemy. 
# Here is a link to the course "https://www.udemy.com/course/machinelearning/"
# In this classification modeling, four machine learning models were implemented, the logistic regression, 
# Support Vector Machines, decision tree classifier, and the random forest classifier.

# Comparing the performances of the models using both RandomizedSearchCV and BayesSearchCV, the models performed 
# almost the same. However, the Logistic regression and Random Forest models performed better using the RandomizedSearchCV
# when compared to using the Bayesian SearchCV for HPO.